SystemUI: Introduce Reverse-engineered Smartspace
Squashed commit of the following:

commit 43ca6d716697b3bf4ab9161b2a7fc205d9f5bcb9
Author: Andrzej Perczak <linux@andrzejperczak.com>
Date:   Tue Mar 8 23:17:46 2022 +0100

    SystemUI: Grant additional permissions for smartspace

    Change-Id: I55df836bf545554eda95085bc71c7cbfca4cfcc5
    Signed-off-by: Andrzej Perczak <linux@andrzejperczak.com>
    Signed-off-by: Pranav Vashi <neobuddy89@gmail.com>
    Signed-off-by: Omkar Chandorkar <gotenksIN@aospa.co>

commit 5872fe59835a9bcbb0a895affecc40f656dacf1f
Author: clarencelol <clarencekuiek@proton.me>
Date:   Wed Dec 11 15:18:34 2024 +0800

    SystemUI: Adapt Smartspace A15-QPR1

    * Building error text
    error: BcSmartspaceView is not abstract and does not override abstract method setBgHandler(Handler) in SmartspaceView
    public class BcSmartspaceView extends FrameLayout implements BcSmartspaceDataPlugin.SmartspaceTargetListener, BcSmartspaceDataPlugin.SmartspaceView {

    Signed-off-by: clarencelol <clarencekuiek@proton.me>

commit 91e8115da418475f2ac559b4162fc083338b4933
Author: aswin7469 <aswinas@pixysos.com>
Date:   Sun Mar 17 15:50:32 2024 +0530

    SystemUI: smartspace: Adapt for 14 QPR2

    Change-Id: I33cd285efc022770b55dab01911ef9e166ba94b5

commit 9d0253be55d7160e2875cdf1351c02b661a863f3
Author: Daniel Jacob Chittoor <djchittoor47@gmail.com>
Date:   Thu Jul 21 01:37:15 2022 +0530

    SystemUI: Implement Reverse-engineered Smartspace

    From SQ3A.220605.009.A1

    [ghostrider-reborn]
    - Adapt to aosp, fix crash on click, misc cleanup

    This squashes the following commits:
    Author: Jake Weinstein <jake@aospa.co>
    Date:   Sat Jun 17 05:29:07 2023 +0900

        SystemUI: Apply "Remove smartspace flag" to KeyguardSmartspaceController

        Change-Id: I7bbd0767d69d54854db691f6c90188a33373f529

    Author: Adithya R <gh0strider.2k18.reborn@gmail.com>
    Date:   Thu May 18 10:40:11 2023 +0530

        fixup! SystemUI: Open google weather on tapping smartspace

        Add null check for smartspaceTarget before hijacking the intent.

        Fixes AOSPA/Tracker#5

        Change-Id: I1cf9057589f88ba1571a5068fb639cbe011f7a67

    Author: Adithya R <gh0strider.2k18.reborn@gmail.com>
    Date:   Thu Jan 26 12:32:39 2023 +0530

        SystemUI: Open google weather on tapping smartspace

        Since smartspace weather activity won't open due to
        caller package (Launcher3) not being google signed,
        hijack the intent to open the google app's exported
        weather activity, which behaves in the same fashion.

        Change-Id: Ic01ede73ab6253bcb301ac794985c3720c5beda3

    Author: Ido Ben-Hur <idoybh2@gmail.com>
    Date:   Wed Mar 15 11:21:00 2023 +0200

        SystemUI: smartspace: Adapt to 13-QPR2

        Change-Id: I142ee24fb02d2234fc1aec50b8d7ff03eba3d5cf
        Signed-off-by: aswin7469 <aswinas@pixysos.com>

    Author: Adithya R <gh0strider.2k18.reborn@gmail.com>
    Date:   Wed Jan 25 18:24:21 2023 +0530

        [WIP] SystemUI: Update smartspace to 13-QPR1

        Credits to https://github.com/BenzoRom/frameworks_packages_SystemUIGoogle (Jason Edson <jaysonedson@gmail.com>) for SystemUIGoogle jar and resources.

        Change-Id: I82c310ca72a5b4ae33b414fda223d127abd0d8d2

    Author: Adithya R <gh0strider.2k18.reborn@gmail.com>
    Date:   Sat Oct 15 15:04:25 2022 +0000

        SystemUI: BcSmartspaceView: Allow setting current page

        Required by launcher smartspace.

        Change-Id: I51d7728b6b2d3d7dfb06e39d1c9363f89795b54f

    Author: jhenrique09 <jhsv09@gmail.com>
    Date:   Wed Oct 5 12:26:30 2022 +0900

        SystemUI: Smartspace: Fix music indication on doze/aod

        Change-Id: If375051a6bf44c67344ad05a4366b6cc663f15d9
        Signed-off-by: Omkar Chandorkar <gotenksIN@aospa.co>

    Author: Adithya R <gh0strider.2k18.reborn@gmail.com>
    Date:   Thu Aug 18 19:11:14 2022 +0530

        SystemUI: Forward-port smartspace to Android 13

        Change-Id: Iddf5c22562b1858e3159fd939c54890e23b29063

    Author: SahilSonar <sss.sonar2003@gmail.com>
    Date:   Mon Oct 16 16:01:54 2023 +0200

        SystemUI: Forward-port smartspace to Android 14

        Change-Id: Ie408c347613af96cf271735071c93e374ae9e06e

    SystemUI: Remove top padding from smartspace date card

    Matches other cards and prevents the content from being too close to
    the page indicator.

    Change-Id: I092055e36883095118ef281232fa3721b7c54aa7

    SystemUI: Add missing permission for Smartspace.

    11-19 10:05:22.800  3994  3994 W BcSmartspaceView: Unable to register Doze Always on content observer.
    11-19 10:05:22.800  3994  3994 W BcSmartspaceView: java.lang.SecurityException: No access to content://settings/secure/doze_always_on: Neither user 10209 nor current process has android.permission.INTERACT_ACROSS_USERS_FULL.

    Change-Id: I39444dd95621ccfbe1dfd737e357145014e440d0
    Co-Authored-By: Anay Wadhera <awadhera@berkeley.edu>
    Co-Authored-By: Adithya R <gh0strider.2k18.reborn@gmail.com>

Change-Id: I4e6fa0cbb063dbd8f802a33b6b70c8f864066b6a